name: Docker Build and Push with Metadata Action

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]
  # 可以手动触发
  workflow_dispatch:


env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - event: pull_request
            push: false
#            tags: pr-${{ github.event.pull_request.number }}-${{ github.sha }}
          - event: push
            ref: refs/heads/main
            push: true
#           tags: latest
          - event: tag
            ref: refs/tags/v*
            push: true
#           tags: ${{ github.ref_name }},latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx with container driver
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # PR 事件
            type=raw,value=pr-{{date 'YYYYMMDD'}}-{{sha}},enable=${{ github.event_name == 'pull_request' }}

            # main 分支推送
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

            # 版本标签
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Login to Docker Hub
        if: matrix.push
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # - name: Login to GHCR
      #   if: matrix.push
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ matrix.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
